// Zirven V2.1 Tailwind preset — generated by scripts/build_brand.py
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "zirven": {
          "night": "#0E0B1F",
          "deep-violet": "#241654",
          "violet": "#5B34E0",
          "electric": "#9671FF",
          "lavender": "#D3C8FF",
          "snow": "#F7F6FC",
          "cyan": "#3DD8E8",
          "cyan-ink": "#0A7A88"
        },
        "ink": {
          "950": "#0E0B1F",
          "900": "#15112B",
          "850": "#1C1735",
          "800": "#241E40",
          "700": "#3A3456",
          "600": "#57516F",
          "500": "#77718F",
          "400": "#9C97B1",
          "300": "#C4C0D3",
          "200": "#E0DEEA",
          "100": "#EEEDF4",
          "50": "#F7F6FC",
          "0": "#FFFFFF"
        },
        "success": "#2EB67D",
        "warning": "#F0A73A",
        "danger": "#E5484D",
        "info": "#0A7A88"
      },
      "fontFamily": {
        "sans": [
          "Readex Pro",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "JetBrains Mono",
          "ui-monospace",
          "monospace"
        ]
      },
      "borderRadius": {
        "xs": "4px",
        "sm": "6px",
        "md": "10px",
        "lg": "14px",
        "xl": "20px",
        "2xl": "28px",
        "pill": "999px"
      },
      "transitionTimingFunction": {
        "summit": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      }
    }
  }
};
